### ISSUE TITLE
Form collections: extra siblings are validated even if untouched

### ISSUE THREAD

**Issue by Actionb** [jrief/django-formset#54]
When you add extra siblings (be it via the `extra_siblings` parameter or by clicking the add button) to a form collection, the data of those extra collections is sent to the server to be validated - regardless of whether they have been touched/filled out by the user. If the extra collections are found to be invalid (which is likely; they're untouched), the user is forced to remove them by hand by clicking the remove button before they can successfully submit the form. 

![extra_siblings_validation](https://user-images.githubusercontent.com/10028803/231122942-321b18f8-7bd8-4e2a-87ea-63e5fa44bfbd.png)
(`ContactCollection` with `testapp.forms.contact.PhoneNumberForm.phone_number` field set to be required) 

This is problematic when the collection is declared with `extra_siblings`: if the user decides not to make use of the offered extra collections, they must remove them although they never added them in the first place. And when using the add button, the user is forced to clean up after themselves.

My understanding was that adding extra siblings is an optional thing; kind of an _invitation_ to add data - not a _requirement._ So extra collections that have not been interacted with should just be ignored and be discarded upon submit (if the `min_siblings` requirement is satisfied, of course). 
What's your take on this?

**Comment by jrief** [comment]
Yes, that's a valid point. I'll try to fix this in version 1 (I'm currently working on).

**Comment by jrief** [comment]
This didn't make it into version 1.0 yet. Sorry, will try to get it into 1.1.

**Comment by jrief** [comment]
I have a not well tested solution.

Please check branch https://github.com/jrief/django-formset/tree/fix-54-empty-collections to see yourself.

**Comment by Actionb** [comment]
This might have revealed or introduced another issue. 

I can now submit a form that circumvents the `min_siblings` requirement by adding an empty sibling and then marking all other siblings for removal. 

* go to `testserver/bootstrap/contact`
* add an empty sibling 
* delete the initial, valid sibling
* send the form

![dj-formset-min-siblings](https://github.com/jrief/django-formset/assets/10028803/aa8cf262-7944-47ed-b058-54c02a94bb4f)




This the "ContactCollection" example from the testapp. The collection in that requires at least one sibling:
https://github.com/jrief/django-formset/blob/cb35d5eb8473cb390a5616244bb2b902ffe5d468/testapp/forms/contact.py#L98-L105

**Comment by jrief** [comment]
Hi Philip,
I'm still working on this issue. Seems to be more tricky than I believed in the first moment. Please wait another few days for it. Thanks

**Comment by jrief** [comment]
I found the reason for this bug. Forms which are marked for removal are still considered valid and hence counted as such. 

They have to be added to the validated holders, so that the `construct_instance` methods know when to delete an entry from the database. I need to look for a generic solution which only counts valid and not marked for removal holders.

**Comment by jrief** [comment]
The lastest commit on this branch has a fix. Please check again.

**Comment by Actionb** [comment]
I get a lot of weird behaviour when I play around with this.
(change values for last name and first name to something valid to follow along)

(1) add another empty sibling
(2)  hit submit:
=> form is rejected with status code 422 although the form should be valid

(1) add another empty sibling
(2) hit submit:
(3) add another empty sibling
=> uncaught error in console: `Uncaught Error: More than one form has id="id_numbers.2.number"`

(1) add another empty sibling
(2) mark the initial sibling with data for removal 
(3) hit submit
=> form is rejected but no field errors are shown


One time, I even managed to produce an internal server error by clicking around on the various form buttons:
```
[2023-06-29 13:39:07,145 log] ERROR: Internal Server Error: /bootstrap/contact
Traceback (most recent call last):
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/projects/django-formset/formset/upload.py", line 99, in post
    return super().post(request, **kwargs)
  File "/data/projects/django-formset/formset/views.py", line 180, in post
    if form_collection.is_valid():
  File "/data/projects/django-formset/formset/collection.py", line 219, in is_valid
    self.full_clean()
  File "/data/projects/django-formset/formset/collection.py", line 271, in full_clean
    if holder.is_valid():
  File "/data/projects/django-formset/formset/collection.py", line 219, in is_valid
    self.full_clean()
  File "/data/projects/django-formset/formset/collection.py", line 242, in full_clean
    if holder.is_valid():
  File "/data/projects/django-formset/formset/utils.py", line 110, in is_valid
    return super().is_valid()
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/forms/forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/forms/boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/forms/forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
  File "/data/projects/django-formset/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 297, in value_from_datadict
    return data.get(name)
AttributeError: 'list' object has no attribute 'get'
[2023-06-29 13:39:07,146 basehttp] ERROR: "POST /bootstrap/contact HTTP/1.1" 500 20335
```

**Comment by Actionb** [comment]
To produce the internal server error:
(0) input a name that isn't John Doe
(1) add empty sibling
(2) hit submit
(3) add 2 empty siblings
(4) hit reset
(5) submit

**Comment by jrief** [comment]
I was able to fix this issue:

> (1) add another empty sibling
(2) hit submit:
=> form is rejected with status code 422 although the form should be valid

I will check the other issues tomorrow.
Many thanks for testing. I really appreciate your feedback.

**Comment by jrief** [comment]
This patch fixed all of your issues. The problem was that I iterated over the list of collections modifying them. This of course is a no-go. I now create a reversed copy and iterate over that list.

**Comment by jrief** [comment]
From my point of view #76 is ready to be merged, although I'd like to add more tests, especially for bulk edits.

@Actionb is there any objection from your side to merge this and does it work in your use-case?

**Comment by Actionb** [comment]
Looks good! This can be closed when you're ready.
