### ISSUE TITLE
Collections for related models do not know their parent instance during validation

### ISSUE THREAD

**Issue by Actionb** [jrief/django-formset#57]
Carrying on from #55 

For (unique) validation, collections for related models may need to know the parent instance of the relation.

Inline formsets are instantiated with the parent instance of the relation, and that instance is passed on to the model forms as data for the InlineForeignKeyField. This way, the parent id is available for validation - most notably unique_together validation.

This does not happen for collections for related models.
You can work around this when editing existing relations of an existing parent: since model_to_dict includes the parent in the initial data of the relation's model form, you just need to include the formfield for the parent in the model form and it validates properly.
However, this doesn't work when you are adding a 'new parent', or a new relation to an existing parent. You need to validate the model form of the parent first, and then you can grab the form's instance and pass it on to the related collections. For example like it is done in [django admin](https://github.com/django/django/blob/57f2b935b34d148c3c0d906fc8256765004b7b77/django/contrib/admin/options.py#L1800).

Currently when adding a new related object that would violate unique constraints, the validation for unique_together is skipped when the form of the new object is first validated, [because the parent field is missing data](https://github.com/django/django/blob/57f2b935b34d148c3c0d906fc8256765004b7b77/django/forms/models.py#L408). Later, when trying to save the duplicate object, the parent instance is available, and a second validation of the form in construct_instance fails as expected due to the unique constraint. The duplicate object is never saved, but the user doesn't know about this, because they are never presented an error.

**Comment by jrief** [comment]
> Inline formsets are instantiated with the parent instance of the relation, and that instance is passed on to the model forms as data for the InlineForeignKeyField. This way, the parent id is available for validation - most notably unique_together validation.

In the Django-admin, this is true. In **django-formset** you have to add that relation field yourself. I usually use a PositiveIntegerField with a hidden input. Please [check this example](https://github.com/jrief/django-formset/blob/releases/1.0.x/testapp/forms/company.py#L16).

The reason I didn't implement it similar to the django-admin is, because I also want to use django-formset for non-relational databases such as MongoDB or JSON fields in a relational database. This means that forms in django-formset are also intended to be used without a model.

Also consider use cases such as 1:1-relations, where such a referring field does not really make sense (ann: django-admin adds such a field for 1:1-relations).

**Comment by Actionb** [comment]
I am aware that I must add that parent field. The issue is that no value for that field is provided for **_new_** forms. 
When you hit the 'add another' button on a collection, the (hidden) field will be included in the new form, but no value will be set. The view does not set the value either, so the form just skips unique validation for the parent field because the field is empty. 

Let's say you have a collection for a m2m table that maps Musicians to Bands as band members with a uniqueness constraint:
```python
class BandMembers(models.Model):
    band = models.ForeignKey('Band', on_delete=models.CASCADE)
    musician = models.ForeignKey('Musician', on_delete=models.CASCADE)

    class Meta:
        unique_together = [('band', 'musician')]
``` 
And the form for the members collection and the top-level form:
```python       

class BandMemberForm(FormMixin, forms.ModelForm):
    id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    # this is the parent when adding members to a band:
    band = forms.ModelChoiceField(queryset=Band.objects, required=False, widget=forms.HiddenInput) 

    class Meta:
        model = BandMembers
        fields = forms.ALL_FIELDS
        widgets = {
            'musician': Selectize(search_lookup='name__icontains'),
        }


class MembersCollection(FormCollection):
    members = BandMemberForm()
    legend = 'Members'
    ...


class BandCollection(FormCollection):
    band = BandForm()
    members = MembersCollection()  # form model has unique_together ('band', 'musician')

    default_renderer = FormRenderer(collection_css_classes='mb-3')
```

Let's say you have created a band with one member, saved it, and then you add the same member again:

![members_collection](https://user-images.githubusercontent.com/10028803/233068349-ef94d300-1d71-443d-b094-4b3a05364041.png)

This should result in an invalid form. But it doesn't. The form validates, because unique constraint validation on the second, duplicate form is skipped, [because `band` in the duplicate form has no value](https://github.com/django/django/blob/57f2b935b34d148c3c0d906fc8256765004b7b77/django/forms/models.py#L408). Saving the form collection just quietly swallows the duplicate selection.

**Comment by jrief** [comment]
Please check the demo named "Company" in branch https://github.com/jrief/django-formset/tree/releases/1.0.x
There I can add a nested elements even, if the parent is missing.

**Comment by jrief** [comment]
Just changed the code so that `testapp.models.Company` has a `unique=True` on field name, but `Team` has a `unique_together = ['name', 'company']` constraint.
This version still has an issue with unique validation. This must be fixed.

**Comment by Actionb** [comment]
Yeah, I just noticed. My test forms were not set up properly, missing a `retrieve_instance` method. The correct error was raised, but for the wrong siblings.

**Comment by jrief** [comment]
I found out why `unique_validation` did not catch errors during the Collection's `full_clean`.

If a field is missing from a form, that's excluded from the unique validation. In the Company's example however, the `MemberForm` does not point to its `Team` instance, and the `TeamForm` does not point to its `Company` instance, hence these fields are excluded from unique validation.

I now change the example code to remove these fields from the exclusion.

**Comment by Actionb** [comment]
Doesn't that just introduce another issue though?

Try creating a new `Company` together with a new `Team`. Model validation will fail, because `Team.company` has no value.
```python
data = {
    "company": {"name": "New Company", "id": None},
    "teams": [{
        "team": {"name": "New Team", "id": None},
        "members": []
    }]
}
collection = CompanyCollection(data=data, instance=Company(name="Foo Corp"))
collection.is_valid()
``` 
Throws the following:
```
Traceback (most recent call last):
  File "/home/philip/projects/django-formset/.venv/lib/python3.10/site-packages/django/forms/models.py", line 492, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/home/philip/projects/django-formset/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1480, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'company': ['This field cannot be null.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/philip/projects/django-formset/formset/collection.py", line 206, in is_valid
    return not self.errors
  File "/home/philip/projects/django-formset/formset/collection.py", line 201, in errors
    self.full_clean()
  File "/home/philip/projects/django-formset/formset/collection.py", line 253, in full_clean
    if holder.is_valid():
  File "/home/philip/projects/django-formset/formset/collection.py", line 206, in is_valid
    return not self.errors
  File "/home/philip/projects/django-formset/formset/collection.py", line 201, in errors
    self.full_clean()
  File "/home/philip/projects/django-formset/formset/collection.py", line 226, in full_clean
    if holder.is_valid():
  File "/home/philip/projects/django-formset/formset/utils.py", line 107, in is_valid
    return super().is_valid()
  File "/home/philip/projects/django-formset/.venv/lib/python3.10/site-packages/django/forms/forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
  File "/home/philip/projects/django-formset/.venv/lib/python3.10/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
  File "/home/philip/projects/django-formset/.venv/lib/python3.10/site-packages/django/forms/forms.py", line 439, in full_clean
    self._post_clean()
  File "/home/philip/projects/django-formset/.venv/lib/python3.10/site-packages/django/forms/models.py", line 494, in _post_clean
    self._update_errors(e)
  File "/home/philip/projects/django-formset/.venv/lib/python3.10/site-packages/django/forms/models.py", line 466, in _update_errors
    self.add_error(None, errors)
  File "/home/philip/projects/django-formset/.venv/lib/python3.10/site-packages/django/forms/forms.py", line 404, in add_error
    raise ValueError(
ValueError: 'TeamForm' has no field named 'company'.
``` 

The validation fails because `Team.company` is not nullable, but the provided value is an unsaved instance.
Then adding an error for the field `company` throws a ValueError, because `company` is not a field on the model form. 

If `company` is excluded by `_get_validation_exclusions` the collection validates fine.
Or am I using the collection incorrectly?

**Comment by jrief** [comment]
I played with this problem during the weekend. Yes, it's true that this is an issue and I'm looking forward for a solution.

The problem is that, `full_clean()` returns a data structure where parent object are not yet instantiated in the database. In example "Company" this means that when adding a Team and adding a child Member to that Team, the latter is not yet materialized in the database, hence can't be uniquely validated.

The approach I will try is to add some extra validation when instantiating the data structure, ie. when calling `formset_valid()`. This means that `formset_valid()` may itself add errors to the collection.

Anyway, thanks for testing this and pointing out those problems. This kind of feedback helps me to improve this library.

**Comment by Actionb** [comment]
Why not validate the parent model form before all collections, and then make the instance from the parent model form available to the collections?

So for this collection:
```python
class CompanyCollection(FormCollection):
    company = CompanyForm()
    teams = TeamCollection()
```
validate `CompanyForm` first. Grab the model form's instance and add it to the data for `TeamCollection`. The model form of `TeamCollection` needs to have a form field for `team` - otherwise, the parent field will fall through validation:

```python
class TeamForm(ModelForm):
    id = fields.IntegerField(
        required=False,
        widget=widgets.HiddenInput,
    )
    team = ModelChoiceField(queryset=Team.objects, required=False, widget=widgets.HiddenInput)

    class Meta:
        model = Team
        fields = ['id', 'name', 'team']
```

Edit `TeamCollection.retrieve_instance` to use the passed in instance:
```python

class TeamCollection(FormCollection):

    def retrieve_instance(self, data):
        parent = # grab the parent instance somehow
        if data := data.get('team'):
            try:
                return self.instance.teams.get(id=data.get('id') or 0)
            except (Team.DoesNotExist, ValueError):
                return Team(name=data.get('name'), company=parent)
```
Repeat for every nested collection; i.e. `TeamCollection` provides the parent for `MemberCollection` through the instance of its `TeamForm`.

**Comment by jrief** [comment]
I actually do not want to make the code for `FormCollection` dependent on any database model. Reason is, that one of my intentions with this library was to be able to edit unstructured data, for instance from JSON fields and/or non-relational databases, such as MongoDB.

Does the code snippet you posted, work in your environment? I mean does it work for forms, where the `Team` and `Member` just have been added, ie. not being materialized in the database?
Django, in order to validate for uniqueness, requires materialized objects. I currently don't see this implemented in your code, but I didn't test for now.

**Comment by jrief** [comment]
I now have a working solution. Since unique validation errors can only be detected if the parent object has been saved to the database, this imo can't be handled in `full_clean()` because this method only validates the integrity of the posted data against existing objects in the database. If however we add a Team and to that Team we add one or more Member objects, the Team does not yet exist in the database.

This solution validates the data and then constructs the instances. If the latter fails, errors are updated.

However, I agree that the current solution requires too much boilerplate code.

**Comment by Actionb** [comment]
Okay, I got too caught up in the idea about 'parent instances', which led me down the wrong path. 

>  Since unique validation errors can only be detected if the parent object has been saved to the database

Yes, that was my thought, too - hence me going on about parent instances. But I was wrong.
You can perform uniqueness validation on a set of forms by using nothing but the form data without requiring the parent instance to be saved/materialized. See the method `ModelFormSet.validate_unique`: 
https://github.com/django/django/blob/c24cd6575f948661fa0ed8b27b79098610dc3ccc/django/forms/models.py#L791

For example in django-admin, this is what it looks like when you attempt to create a **_new_** company with duplicate new teams in django-admin:

![django-admin-unique-validation-new-object](https://user-images.githubusercontent.com/10028803/234221287-3f7f798b-66b0-4792-9347-a68052960ada.png)

The company (the parent instance) is never saved, but the uniqueness of the teams was checked. The validation errors are raised by `ModelFormSet.validate_unique`.  

This is what I was after, but I completely missed that part of the formset validation chain, making me think the above validation was done on the ModelForm or the model instance (thus requiring a parent instance).

**Comment by jrief** [comment]
Actually, `validate_unique` is called implicitly by the Collection's `full_clean` method. And it detects validation errors if the parent model is materialized, but fails if otherwise – which forces me to catch `IntegrityError`-s and revalidate during instantiation, which is somehow hacky.

Of course it would be really great if "You can perform uniqueness validation on a set of forms by using nothing but the form data without requiring the parent instance to be saved/materialized.". I have to check that.

The current solution works, but is not a really clean solution, imo. I will try to pilfer parts of the Django formset code and apply them here. Anyway, thanks for reporting.

**Comment by jrief** [comment]
Thanks to your hint, I finally found a working solution to validate not yet materialized forms during the `full_clean` process.
You can have a look at this branch: https://github.com/jrief/django-formset/tree/releases/1.0.x

However, I'm still struggling to find a solution which is generic enough to get rid of the boilerplate code in my demo collections.

**Comment by Actionb** [comment]
Looks good. This validates new objects as you'd expect.

**Comment by jrief** [comment]
I'm currently working on a solution to get rid of the boilerplate code required for `model_to_dict` and `construct_instance`. For `model_to_dict` I already have a working solution.

**Comment by Actionb** [comment]
I  finally had time updating the tests ([here](https://github.com/Actionb/django-formset/blob/issue-57-unique-validation/testapp/tests/test_collection_unique_validation.py)) that I have written for this issue, and everything seems to validate properly. 

Looks like it's fixed, good job.

**Comment by jrief** [comment]
Thanks for adding some additional tests, I already started to do so as well.

However, please use pytest for testing, rather than the Django `TestCase` class. In **django-formset** everything (incl. Playwright) is based on pytest – which imho is the far better testing framework.

**Comment by Actionb** [comment]
> However, please use pytest for testing, rather than the Django TestCase class. In django-formset everything (incl. Playwright) is based on pytest – which imho is the far better testing framework.

Yes that makes sense. I have updated the tests: https://github.com/Actionb/django-formset/blob/issue-57-unique-validation/testapp/tests/test_collection_unique_validation.py
